Prob 5

In [34]:
import numpy as np

p_7 = np.array([[0.47500716], [-0.79485077]])
R_47 = np.array([[0.12731093, -0.99186286], [0.99186286, 0.12731093]])
q_4 = np.array([[0.12270238], [0.27918390]])

In [36]:
R_47.T.dot((q_4-p_7))

array([[1.02044285],
       [0.48617438]])

In [37]:
import numpy as np

p_9 = np.array([[0.15013585], [0.53729064]])
R_49 = np.array([[-0.54424277, -0.83892777], [0.83892777, -0.54424277]])
q_9 = np.array([[-0.92635228], [-0.72281123]])

In [38]:
R_49.dot(q_9) + p_9

array([[1.26068279],
       [0.15353277]])

Draw the relationship map and the equation

Prob 7 

In [20]:
import numpy as np

R1 = np.array([[0.17231657, -0.86627811, -0.47485016], [0.97301198, 0.34694246, -0.11030412], [0.48743591, -0.40706390, 0.74197689]])
R2 = np.array([[-0.21045390, -0.33106999, 0.91983793], [-0.33312338, 0.90888528, 0.25091108], [-0.91909628, -0.25361430, -0.30156561]])
R3 = np.array([[0.21890413, -0.92268282, -0.63458470], [1.05034892, 0.16679912, 0.15693454], [-0.02862355, -0.51013469, 0.86431030]])
R4 = np.array([[1.03299000, 0.00577202, 0.46365207], [0.52470367, 0.32750637, -0.72506492], [-0.31548650, 0.94856451, 0.45428530]])
R5 = np.array([[-0.96514921, 0.22308844, -0.13681576], [-0.26024821, -0.87317955, 0.41210234], [-0.02752945, 0.43334631, 0.90080692]])

In [25]:
np.linalg.det(R5)

0.9999999999586612

In [27]:
R5.T.dot(R5)

array([[ 9.99999999e-01, -2.30385640e-09,  7.29394422e-09],
       [-2.30385640e-09,  1.00000000e+00,  4.54350380e-09],
       [ 7.29394422e-09,  4.54350380e-09,  9.99999998e-01]])

In [41]:
import numpy as np

R_0 = np.array([[0.15747570, 0.01054653, -0.98746654], [-0.09915924, 0.99505807, -0.00518576], [0.98253186, 0.09873306, 0.15774325]])
R_1 = np.array([[0.45444337, 0.44159621, 0.07732724], [-0.55941175, -0.12052851, -0.70682956], [0.51801993, 0.62304591, -0.89316392]])
R_2 = np.array([[-0.41218907, 0.04004365, -0.47016150], [-0.61442880, -0.07646181, -0.57137001], [-0.11118421, 0.98444372, -0.90815816]])
R_3 = np.array([[0.15747570, -0.09915924, 0.98253186], [0.01054653, 0.99505807, 0.09873306], [-0.98746654, -0.00518576, 0.15774325]])

In [32]:
np.linalg.det(R_3)

1.000000004316984

In [34]:
R_3.T.dot(R_3)

array([[ 9.99999993e-01,  3.54099950e-09,  2.31922881e-09],
       [ 3.54099950e-09,  1.00000001e+00, -3.02071220e-09],
       [ 2.31922881e-09, -3.02071220e-09,  1.00000001e+00]])

In [45]:
R_0 * -1

array([[-0.1574757 , -0.01054653,  0.98746654],
       [ 0.09915924, -0.99505807,  0.00518576],
       [-0.98253186, -0.09873306, -0.15774325]])

In [46]:
R_3

array([[ 0.1574757 , -0.09915924,  0.98253186],
       [ 0.01054653,  0.99505807,  0.09873306],
       [-0.98746654, -0.00518576,  0.15774325]])

Prob 9 

## transpose 之后减去V，不transpose 则加上p

In [10]:
import numpy as np


T_95 = np.array([[0.83076029, 0.50215127, 0.24016961, -0.23289293], [0.04382999, -0.48914390, 0.87110113, -0.18801268], [0.55490204, -0.71314960, -0.42837061, 0.70303041], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
p_9 = np.array([[0.46507614], [-0.27464321], [0.00377920]])

T_95

array([[ 0.83076029,  0.50215127,  0.24016961, -0.23289293],
       [ 0.04382999, -0.4891439 ,  0.87110113, -0.18801268],
       [ 0.55490204, -0.7131496 , -0.42837061,  0.70303041],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [3]:
def extractRT(t):
    r = np.matrix([[t[0][0],t[0][1],t[0][2]],[t[1][0],t[1][1],t[1][2]],[t[2][0],t[2][1],t[2][2]]])
    p = np.matrix([[t[0][3]],[t[1][3]],[t[2][3]]])
    return r,p

In [12]:
r,p=extractRT(T_95)

In [13]:
v = np.matmul(r.T, p)
v

matrix([[ 0.18839422],
        [-0.52634808],
        [-0.52086943]])

In [14]:
newP = np.matmul(r.T, p_9) - v
newP

matrix([[0.18803205],
        [0.89153157],
        [0.39170567]])

In [154]:
[[-1.06818757819], [-0.0225880313576], [0.137456874288]]

[[-1.06818757819], [-0.0225880313576], [0.137456874288]]

In [155]:
import numpy as np

T_81 = np.array([[0.23319927, 0.64338339, 0.72916110, -0.14499569], [-0.94671597, 0.32150308, 0.01909555, -0.70914963], [-0.22214178, -0.69476153, 0.68407561, -0.09615535], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
p_1 = np.array([[-0.73542634], [0.43762420], [0.73257930]])

In [156]:
r,p=extractRT(T_81)

In [158]:
newP = np.matmul(r, p_1) + p
newP

matrix([[0.49923189],
        [0.14177676],
        [0.26430874]])

In [159]:
import numpy as np

T_54 = np.array([[-0.78480162, 0.40257459, 0.47119012, -0.68175557], [0.53696840, 0.82131039, 0.19265042, -0.55358209], [-0.30943717, 0.40420657, -0.86073555, 0.90333128], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
p_5 = np.array([[0.82222292], [-0.11787068], [-0.57198160]])

In [160]:
r,p=extractRT(T_54)

In [161]:
v = np.matmul(r.T, p)
v

matrix([[-0.04173749],
        [-0.36398775],
        [-1.20541366]])

In [165]:
newP = np.matmul(r.T, p_5) - v
newP

matrix([[-0.48984485],
        [ 0.36698667],
        [ 2.06245403]])

If we need to inverse the vector, r.T * -v

Prob 10

In [189]:
import numpy as np

T_89 = np.array([[-0.50918572, 0.84263683, 0.17519442, 0.65827217], [-0.66079321, -0.25233278, -0.70688082, 0.96351552], [-0.55143652, -0.47570090, 0.68529294, 0.09148563], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
v_8 = np.array([[-0.14927652], [-0.93497573], [0.54084026]])

In [190]:
r,p=extractRT(T_89)
r.T

matrix([[-0.50918572, -0.66079321, -0.55143652],
        [ 0.84263683, -0.25233278, -0.4757009 ],
        [ 0.17519442, -0.70688082,  0.68529294]])

In [191]:
newv = np.matmul(r.T, v_8)
newv

matrix([[ 0.39559602],
        [-0.14713907],
        [ 1.00539801]])

In [47]:
import numpy as np

T_29 = np.array([[-0.40682859, 0.26803726, -0.87329636, 0.23186487], [-0.90392765, -0.25618297, 0.34246911, 0.86585822], [-0.13192917, 0.92872295, 0.34650885, -0.42021570], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
v_2 = np.array([[0.13491336], [0.42727426], [0.92915831]])

In [48]:
r,p=extractRT(T_29)
r.T

matrix([[-0.40682859, -0.90392765, -0.13192917],
        [ 0.26803726, -0.25618297,  0.92872295],
        [-0.87329636,  0.34246911,  0.34650885]])

In [49]:
newv = np.matmul(r.T, v_2)
newv

matrix([[-0.56369471],
        [ 0.78963207],
        [ 0.35047047]])