Prob 1

In [12]:
## 此题注意yzy变换
import numpy as np

theta1 = 1.96
theta2 = -3.11
theta3 = -0.22

In [13]:
import math
def matrixX(r):
    return np.matrix([[1,0,0],
           [0, math.cos(r), -math.sin(r)],
           [0,math.sin(r), math.cos(r)]])
def matrixY(r):
    return np.matrix([[math.cos(r),0,math.sin(r)],
           [0, 1,0],
           [-math.sin(r),0, math.cos(r)]])
def matrixZ(r):
    return np.matrix([[math.cos(r),-math.sin(r),0],
           [math.sin(r), math.cos(r), 0],
           [0,0,1]])

In [14]:
m1 = matrixZ(theta1)
m2 = matrixY(theta2)
m3 = matrixZ(theta3)

In [15]:
from numpy.linalg import multi_dot
multi_dot([m1,m2,m3])

matrix([[ 0.57202979, -0.82014527,  0.01198589],
        [-0.81965339, -0.57211382, -0.02922502],
        [ 0.03082606,  0.00689331, -0.99950099]])

Prob 2

ZYX calculator

https://www.andre-gaschler.com/rotationconverter/

In [16]:
## prob 4

In [33]:
import numpy as np

p_7in0 = np.matrix([[-0.48819525], [-0.07335992], [-0.54055216]])
R_7in0 = np.matrix([[0.05849198, 0.04529358, 0.99725984], [-0.95382980, -0.29226271, 0.06921869], [0.29459702, -0.95526488, 0.02610734]])

In [34]:
R_7in0.T

matrix([[ 0.05849198, -0.9538298 ,  0.29459702],
        [ 0.04529358, -0.29226271, -0.95526488],
        [ 0.99725984,  0.06921869,  0.02610734]])

In [35]:
R_7in0.T * p_7in0  * -1

matrix([[ 0.11782768],
        [-0.51569875],
        [ 0.50604777]])

In [28]:
R_1in3.T

matrix([[-0.98831703, -0.14896034,  0.03225302],
        [-0.11984985,  0.89029839,  0.4393231 ],
        [-0.09415653,  0.43032498, -0.89774994]])

In [29]:
[[0.872367426773], [-0.111337543938], [-0.129519248704]]

[[0.872367426773], [-0.111337543938], [-0.129519248704]]

Prob 4

In [23]:
import numpy as np

p_9in4 = np.array([[-0.36889446], [-0.47386900], [-0.86616937]])
R_9in4 = np.array([[-0.96103444, -0.01200106, -0.27616804], [-0.09867836, 0.94812697, 0.30218841], [0.25821578, 0.31766528, -0.91236691]])

In [11]:
import numpy as np

p_4in8 = np.array([[0.85411359], [0.54775763], [-0.45612112]])
R_4in8 = np.array([[0.87358700, -0.01693152, -0.48637339], [0.02348694, -0.99676333, 0.07688456], [-0.48610093, -0.07858878, -0.87036182]])

In [12]:
RI = R_4in8.T
RI

array([[ 0.873587  ,  0.02348694, -0.48610093],
       [-0.01693152, -0.99676333, -0.07858878],
       [-0.48637339,  0.07688456, -0.87036182]])

In [13]:
RI.dot(p_4in8) * -1

array([[-0.98072858],
       [ 0.52460016],
       [-0.02368639]])

Prob 5

In [47]:
import numpy as np

T_6in1 = np.matrix([[0.82364713, -0.08492977, -0.56070699, -0.10370133], [0.18044523, -0.89808752, 0.40109641, -0.01845371], [-0.53762898, -0.43153881, -0.72438204, -1.22891608], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
T_8in1 = np.matrix([[0.05434452, -0.03934770, -0.99774668, 0.45609973], [0.94903521, 0.31270275, 0.03935942, -0.94892087], [0.31044943, -0.94903569, 0.05433604, -0.05861383], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

In [48]:

## be care ful here is the inverse and 转换原本作标而非code中坐标
(T_6in1.I * T_8in1)

matrix([[ 0.04910297,  0.53424618, -0.84390161, -0.33600822],
        [-0.99090312,  0.13205309,  0.02594208,  0.28306633],
        [ 0.12529927,  0.83495089,  0.53587042, -1.53483734],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

Prob 6

https://math.stackexchange.com/questions/258775/from-a-vector-to-a-skew-symmetric-matrix

In [ ]:
## 注意python 中的写法需要以【【】，【】，【】】 的格式

Prob 7

In [79]:
def woperationM(w):
    return np.array([[0,-w.item(2),w.item(1)],[w.item(2),0,-w.item(0)],[-w.item(1),w.item(0),0]])

In [80]:
import numpy as np

a = np.matrix([[-5], [ 1], [-1]])

In [81]:
woperationM(a)

array([[ 0,  1,  1],
       [-1,  0,  5],
       [-1, -5,  0]])

Prob 8

In [89]:
import numpy as np

v_in2 = np.array([[-3], [ 8], [10]])

In [90]:
woperationM(v_in2)

array([[  0, -10,   8],
       [ 10,   0,   3],
       [ -8,  -3,   0]])