In [12]:
def woperationM(w):
    return np.matrix([[0,-w.item(2),w.item(1)],[w.item(2),0,-w.item(0)],[-w.item(1),w.item(0),0]])
def inverswop(w):
    
    return np.matrix([[w.item(7)],[w.item(2)],[w.item(3)]])
def voperationM(w):
    return np.array([[0,-w.item(2),w.item(1),w.item(3)],[w.item(2),0,-w.item(0),w.item(4)],[-w.item(1),w.item(0),0,w.item(5)],[0,0,0,0]])
def soperation(s):
    tmp = np.matrix([s.item(0),s.item(1),s.item(2)])
    w = woperationM(tmp)
    return np.matrix([[w.item(0),w.item(1),w.item(2),s.item(3)],
                      [w.item(3),w.item(4),w.item(5),s.item(4)],
                      [w.item(6),w.item(7),w.item(8),s.item(5)],
                      [0,0,0,0]])

In [13]:
def sconver(w,q):

    return -1*woperationM(w)*q

PROB 1

In [64]:
import numpy as np

theta = 0.23

In [66]:
m = np.matrix([[0,1,0,2],[-1,0,0,2],[0,0,1,0],[0,0,0,1]])

In [98]:
w = np.matrix([0,-0.39,0])
q = np.matrix([[0],[0],[-2]])

-1*woperationM(w)*q


matrix([[-0.78],
        [ 0.  ],
        [ 0.  ]])

In [18]:
s = np.matrix([1,0,0,0,0,0])

In [69]:
from scipy.linalg import expm
T = expm(soperation(s)*theta)*m

T

matrix([[ 0.        ,  0.9736664 ,  0.22797752,  1.94733279],
        [-1.        ,  0.        ,  0.        ,  2.        ],
        [ 0.        , -0.22797752,  0.9736664 , -0.45595505],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [76]:
R = np.matrix([[ 0.        ,  0.9736664 ,  0.22797752],[-1.        ,  0.        ,  0.       ],[ 0.        , -0.22797752,  0.9736664 ]])

In [77]:
R

matrix([[ 0.        ,  0.9736664 ,  0.22797752],
        [-1.        ,  0.        ,  0.        ],
        [ 0.        , -0.22797752,  0.9736664 ]])

In [ ]:
P = np.matrix([])

In [78]:
def extractRT(t):
    r = np.matrix([[t[0][0],t[0][1],t[0][2]],[t[1][0],t[1][1],t[1][2]],[t[2][0],t[2][1],t[2][2]]])
    p = np.matrix([[t[0][3]],[t[1][3]],[t[2][3]]])
    return r,p

In [82]:
r,p = extractRT([[ 0.        ,  0.9736664 ,  0.22797752,  1.94733279],
        [-1.        ,  0.        ,  0.        ,  2.        ],
        [ 0.        , -0.22797752,  0.9736664 , -0.45595505],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [83]:
r

matrix([[ 0.        ,  0.9736664 ,  0.22797752],
        [-1.        ,  0.        ,  0.        ],
        [ 0.        , -0.22797752,  0.9736664 ]])

In [91]:
r * p


matrix([[ 1.8433853 ],
        [-1.94733279],
        [-0.89990315]])

In [92]:
np.dot(r,p)

matrix([[ 1.8433853 ],
        [-1.94733279],
        [-0.89990315]])

Prob 2

In [189]:
w = np.matrix([1,0,0])
q = np.matrix([[0],[2],[0]])
sconver(w,q)

matrix([[ 0],
        [ 0],
        [-2]])

Prob 4

In [22]:
w=np.matrix([-1,0,0])
q=np.matrix([[0],[2],[0]])
def sconver(w,q):

    return -1*woperationM(w)*q

In [21]:
import numpy as np

theta = np.array([[0.01000000, -0.57000000, -0.78000000]])
T_2_in_0 = np.array([[-0.43201542, 0.41415363, 0.80114883, 0.21026265], [0.73220875, 0.67969140, 0.04347358, -0.10987661], [-0.52652923, 0.60538943, -0.59688408, -0.52835984], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

In [23]:
import numpy as np

theta = np.array([[-0.31, 0.55, 0.86]])

In [17]:
from scipy.linalg import expm

In [112]:
w=np.matrix([0,1,0])
q=np.matrix([[0],[2],[6]])
-1*woperationM(w)*q


matrix([[-6],
        [ 0],
        [ 0]])

In [113]:
import numpy as np

theta = np.array([[0.52, 0.84, 0.52]])

In [114]:

s1=np.matrix([0,0,0,0,1,0])
s2=np.matrix([0,0,0,-1,0,0])
s3=np.matrix([0,1,0,-6,0,0])
m = np.matrix([[1,0,0,0],[0,0,1,4],[0,-1,0,6],[0,0,0,1]])

In [ ]:
[[0,0,0],[0,0,0],[0,0,0],[0,0,0],[-1,-1,-1],[0,0,0]]

In [116]:
from numpy.linalg import multi_dot
t1 = expm(soperation(s1)*theta[0][0])
t2 = expm(soperation(s2)*theta[0][1])
t3 = expm(soperation(s3)*theta[0][2])
T01 = multi_dot([t1,t2,t3,m])
T01

matrix([[ 0.86781918, -0.49688014,  0.        , -0.84      ],
        [ 0.        ,  0.        ,  1.        ,  4.52      ],
        [-0.49688014, -0.86781918,  0.        ,  6.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [38]:
[[0, 1, 0, 6], [-0.987100101014, 0, 0.160104311555, 0.31], [0.160104311555, 0, 0.987100101014, -2], [0, 0, 0, 1]]

[[0, 1, 0, 6],
 [-0.987100101014, 0, 0.160104311555, 0.31],
 [0.160104311555, 0, 0.987100101014, -2],
 [0, 0, 0, 1]]

In [57]:
T01.I *  T_2_in_0

matrix([[ 0.64571233, -0.67246829, -0.36172086,  7.43633185],
        [ 0.73220875,  0.6796914 ,  0.04347358, -0.10987661],
        [ 0.21662395, -0.2929266 ,  0.93127229, -2.79776746],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [63]:
(7.43633185 ** 2  + (-0.10987661)**2 +  (-2.79776746)**2)** (1/2)

7.94598055704797

In [110]:
import numpy as np

theta = np.array([[-0.99000000], [0.72000000], [-0.64000000], [0.19000000], [0.24000000], [-0.40000000], [-0.07000000], [-0.71000000]])
dtheta = np.matrix([[-0.35000000], [0.65000000], [-0.79000000], [0.23000000], [0.58000000], [0.96000000], [-0.49000000], [0.32000000]])
jacobian = np.matrix([[-0.18885889, -0.18885889, -0.18885889, 0.00000000, 0.00000000,  0.00000000, 0.00000000, 1.00000000], [0.64010352, 0.64010352, 0.64010352, -0.75836188, 0.00000000, 0.00000000,  0.00000000, -0.00000000], [-0.74471457, -0.74471457, -0.74471457, -0.65183377, 0.00000000,  0.00000000, 0.00000000, 0.00000000], [0.54136445, 0.69831758, -0.47457932, 1.07366754, -0.00000000,  -0.00000000, -0.00000000, 0.00000000], [-1.79847088, -3.29066797, -4.65426067, -5.21467017, 0.65183377,  0.65183377, 0.65183377, 0.00000000], [-1.68312677, -3.00551611, -3.88011761, 6.06689501, -0.75836188,  -0.75836188, -0.75836188, 2.00000000]])
T_1in0 = np.array([[-0.60270093, 0.52317461, 0.60252794, -3.07519304], [-0.77529602, -0.56263292, -0.28698481, 1.71867394], [0.18885889, -0.64010352, 0.74471457, 0.45652509], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

In [111]:
jacobian * dtheta

matrix([[ 0.41254086],
        [-0.48807396],
        [ 0.21498837],
        [ 0.88629007],
        [ 1.65244788],
        [ 2.93990769]])